#!/bin/sh

workspace="/home/scratch.yilinz_t19x/git/dla_amod/"
histdir="${workspace}../amod_tests/datadistri/alexnet_129_old_even_hist/"
range_outdir="${workspace}../amod_tests/datadistri/alexnet_129_old_even_hist/log_range"
data_outdir="${workspace}../amod_tests/datadistri/alexnet_129_old_even_hist/log_data"
config="${workspace}models/bvlc_alexnet/train_val.prototxt"
model="${workspace}models/bvlc_alexnet/bvlc_alexnet.caffemodel"
maxtime=180
hist_file_num=500

rm -rf ${range_outdir} ${data_outdir}
mkdir ${range_outdir} ${data_outdir}

cp ${config} ${range_outdir}
cp ${config} ${data_outdir}
# Collect the data range of each blob
${workspace}amod_scripts/submit_jobs.pl -model_def ${config} -pre_trained ${model} -maxtime ${maxtime} -out_dir ${range_outdir} -skip 0 -interval 2 -histdir $histdir -hist_mode 0
# submit the failed tasks again
${workspace}amod_scripts/pixiu.py --dir ${range_outdir} --process $hist_file_num --amod_dir ${workspace}

# merge the histogram generated by each process
${workspace}amod_scripts/merge_hist.py --model ${config} --file_num ${hist_file_num} --dir ${histdir}
# Collect the histogram of each blob
${workspace}amod_scripts/submit_jobs.pl -model_def ${config} -pre_trained ${model} -maxtime ${maxtime} -out_dir ${data_outdir} -skip 0 -interval 2 -histdir $histdir -hist_mode 1
# submit the failed tasks again
${workspace}amod_scripts/pixiu.py --dir ${data_outdir} --process $hist_file_num --amod_dir ${workspace}
# merge the histogram generated by each process
${workspace}amod_scripts/merge_hist.py --model ${config} --file_num ${hist_file_num} --dir ${histdir} --skip false --log hist_collect.log
# get the final top1/5
${workspace}amod_scripts/amod_result_parsing.py --log_dir ${data_outdir} --line 3
